# Generated by Django 5.0.2 on 2024-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnewblog',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
