# Generated by Django 5.0.2 on 2024-02-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_commentnewblog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnewblog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.commentnewblog'),
        ),
    ]
