# Generated by Django 5.0.2 on 2024-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecontact',
            name='address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecontact',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecontact',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
