# Generated by Django 5.0.2 on 2024-02-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mecontact_address_mecontact_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecontact',
            name='address',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
