# Generated by Django 5.0.2 on 2024-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_rooms_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='children',
            field=models.IntegerField(null=True),
        ),
    ]
